<?php

$travels = [
    [
        "departure" => "Roma",
        "arrival" => "Tokyo",
        "departure_date" => "2021/09/01",
        "return_date" => "2021/09/14",
        "accommodation_type" => "hotel",
        "rooms" => 1,
        "adults_guests" => 2,
        "kids_guests" => 0,
        "neonates_guests" => 0,
    ],
    [
        "departure" => "Bari",
        "arrival" => "Parigi",
        "departure_date" => "2021/12/23",
        "return_date" => "2021/12/30",
        "accommodation_type" => "Bed and Breakfast",
        "rooms" => 1,
        "adults_guests" => 2,
        "kids_guests" => 0,
        "neonates_guests" => 0,
    ],
    [
        "departure" => "Milano",
        "arrival" => "Zante",
        "departure_date" => "2021/08/13",
        "return_date" => "2021/08/20",
        "accommodation_type" => "Casa vacanze",
        "rooms" => 4,
        "adults_guests" => 4,
        "kids_guests" => 0,
        "neonates_guests" => 0,
    ],
    [
        "departure" => "Napoli",
        "arrival" => "Berlino",
        "departure_date" => "2022/02/01",
        "return_date" => "2022/02/07",
        "accommodation_type" => "hotel",
        "rooms" => 1,
        "adults_guests" => 2,
        "kids_guests" => 1,
        "neonates_guests" => 1,
    ],
    [
        "departure" => "Bari",
        "arrival" => "Milano",
        "departure_date" => "2021/07/25",
        "return_date" => "2021/07/31",
        "accommodation_type" => "Bed and Breakfast",
        "rooms" => 2,
        "adults_guests" => 4,
        "kids_guests" => 1,
        "neonates_guests" => 0,
    ],
    [
        "departure" => "Napoli",
        "arrival" => "Londra",
        "departure_date" => "2021/11/15",
        "return_date" => "2021/12/15",
        "accommodation_type" => "Appartamento",
        "rooms" => 1,
        "adults_guests" => 1,
        "kids_guests" => 0,
        "neonates_guests" => 0,
    ]
];

return $travels;
